README.md
lib/passport-saml/saml.js
test/static/acme_tools_com.xml
test/static/expected metadata without key.xml
test/static/expected metadata.xml
test/tests.js

This is a PR that mirrors the changes made by @achingbrain. It has been modified only where necessary to fit on master.

Specify SingleLogoutService callback url

---

README.md

1. public, not private
2. a signing certificate and not an encryption certificate

Fixes #170: Clarify that the certificate are looking for is:

---

test/tests.js

fixes https://github.com/bergie/passport-saml/issues/346

Fix for failing test

---

package.json

[Node version was changed to Node 6](https://github.com/bergie/passport-saml/commit/d2c89947fca1fa79365f5819a0e7326ebc94728a). Node version was not updated to package.json so let's do it in this PR.

Update Node version in package.json to >=6

---

package.json

This version contains https://github.com/yaronn/xml-crypto/pull/172 which we need.  Thanks.

update xml crypto to 1.1.4

---

lib/passport-saml/saml.js

This PR has a change requested in issue #393 , post authentication profile object will contain `inResponseTo`.

fix #393 adding 'inResponseTo' in the profile

---

README.md

@stavros-wb @cjbarth added passReqToCallback to README

added passReqToCallback to docs

---

package.json
yarn.lock

Currently running into this: https://github.com/auth0/node-xml-encryption/issues/55

Upgrade xml-encryption to 1.0.0

---

README.md
lib/passport-saml/saml.js
test/tests.js

A regression has been reported in #390 . Reverting until that's that resolved. 
See: https://github.com/bergie/passport-saml/commit/7e2de2d4e22d1562eccd5d487ac24071226e9492#commitcomment-37214216 for discussion.

Revert "convert privateCert to PEM for signing"

---

package-lock.json
package.json

* Bump xml-crypto from 1.4.0 to 1.5.3
* Include package-lock.json in repo
May possibly help with https://github.com/node-saml/passport-saml/issues/456 ?

Upgrade xml-crypto dependancy

---

src/passport-saml/algorithms.ts
src/passport-saml/index.ts
src/passport-saml/inmemory-cache-provider.ts
src/passport-saml/saml-post-signing.ts
src/passport-saml/saml.ts
src/passport-saml/strategy.ts
tsconfig.json

Secondary files were changed to typescript

Ts secondary files

---

src/passport-saml/saml-post-signing.ts
src/passport-saml/saml.ts

This adds the deprecation notice for `privateCert` in favor of `privateKey`. It also fixes a bug introduced in the refactoring of `privateCert` to `privateKey`.

Add deprecation notice for privateCert; fix bug

---

src/passport-saml/saml.ts

I hope it fixes #499, but if it does not - it is still a useful change

support windows line breaks in keys

---

.gitignore
package-lock.json
package.json

This was found during an `npm audit`

Update xml-crypto to v2.1.1

---

package-lock.json
package.json

This update xmldom to a non vulnerable version.

Update xml-encryption to v1.2.3

---

package-lock.json
package.json

Reverts node-saml/passport-saml#560
The `package-lock.json` file might be corrupt.

Revert "Update xml-encryption to v1.2.3"

---

src/passport-saml/index.ts

Add export for AuthenticateOptions

Simplify typings

---

.github/workflows/workflow.yml

Add support for automatically running code coverage reports when making a PR.

Add code coverage workflow

---

.release-it.json
package-lock.json
package.json
src/index.ts
src/multiSamlStrategy.ts
src/types.ts
test/multiSamlStrategy.spec.ts
test/strategy.spec.ts

Update code to support `node-saml@4.0.0-beta.3`.

Update to support node-saml@4.0.0-beta.3

---

README.md

Fix some typos in the README for the new badges.

Update badges for scoped package

---

package-lock.json
package.json

Update `@node-saml/node-saml` to `4.0.0-beta.5`.

Update node-saml to beta 5

---

CHANGELOG.md
package-lock.json
package.json

Update the changelog to include information about the recent vulnerability fix and update related changelog and build tools.

Update changelog and related tools

---

.release-it.json
package-lock.json
package.json

Update changelog and build tools.

Update changelog build tools

---

package.json

Clean working folder before doing a release build.

Clean working folder before doing a release build

---

.github/workflows/workflow.yml
package.json

Update to Node 18

---

package-lock.json
package.json
test/multiSamlStrategy.spec.ts
test/strategy.spec.ts

Update dependency @node-saml/node-saml to version 5 and adjust code to work with the breaking changes.

Update to @node-saml/node-saml v5

---

package-lock.json

Update all nested dependencies by deleting `package-lock.json` and `node_modules` and then doing an `npm i`.

Update nested dependencies
