- README.md
- lib/passport-saml/strategy.js
- test/tests.js
if `passReqToCallback` options is truthy, `req` will be passed as the first argument to the verify callback (default: `false`)
see: [Association in Verify Callback](http://passportjs.org/guide/authorize/)
This PR makes passport-saml compatible with
- [passport-local](https://github.com/jaredhanson/passport-local)
- [passport-openid](https://github.com/jaredhanson/passport-openid)
- [passport-oauth1](https://github.com/jaredhanson/passport-oauth1)
- [passport-oauth2](https://github.com/jaredhanson/passport-oauth2)
and many others based on them (like [passport-twitter](https://github.com/jaredhanson/passport-twitter) or [passport-facebook](https://github.com/jaredhanson/passport-facebook)).
> add `passReqToCallback` option to be compatible with other strategies

- lib/passport-saml/saml.js
Currently, when generating a LogoutRequest, `options.entryPoint` is used as the `@Destination` property. This will not validate from an IdP, resulting in the user **not** logging out. Setting `@Destination` to `options.logoutUrl` fixes this issue, allowing the user to log out of the IdP and be correctly redirected back.
> Use logoutUrl for generateLogoutRequest

- README.md
- lib/passport-saml/saml.js
- test/tests.js
Hi,
Is it possible to add @ForceAuthn to SAML AuthnRequest? It is configurable by forceAuthn boolean option (default false)
> Add parameter @ForceAuthn to SAML AuthnRequest. 

- lib/passport-saml/saml.js
- test/tests.js
Add Destination attribute to the LogoutResponse to be compliant with the spec.
See section 3.4.5.2 and 3.5.5.2 of http://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
> If the message is signed, the Destination XML attribute in the root SAML element of the protocol message MUST contain the URL to which the sender has instructed the user agent to deliver the message. The recipient MUST then verify that the value matches the location at which the message has been received.
Without the Destination attribute, PingFederate (at least in 6.10) will reject the LogoutResponse.
> Add Destination attribute to LogoutResponse

- lib/passport-saml/saml.js
- test/samlTests.js
Noticed an issue where you a query string in an entrypoint will not be handled correctly. For example:
```
{
entryPoint: 'https://exampleidp.com/path?key=value'
}
```
would end up causing a URL such as `https://exampleidp.com/path?key=value?SAMLRequest=...`
The existing tests were a little complicated for me to figure out where to throw some tests to validate behavior. I decided to write some simple tests separately to expose the issue and validate this fixes it.
Let me know if there is anything else you would like to see.
> Fix issue where query strings in entry points mess up entryPoint URLs

- lib/passport-saml/saml.js
- test/tests.js
This PR adds `sessionIndex` property to returned profile if one is defined in `AuthnStatement`. In addition it adds `saml2p:SessionIndex` element to the generated logout request if `req.user.sessionIndex` exists.
Related to #81. Tested with WSO2 5.0.0 with following logout URI handler:
```javascript
app.get('/logout', function(req, res) {
if (req.user == null) {
return res.redirect('/');
}
return samlStrategy.logout(req, function(err, uri) {
return res.redirect(uri);
});
});
```
> SessionIndex / WSO2 logout

- lib/passport-saml/saml.js
- test/static/expected metadata without key.xml
- test/tests.js
According to [SAML:2.0:metadata](http://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd):
```xml
...
<element name="KeyDescriptor" type="md:KeyDescriptorType"/>
<complexType name="KeyDescriptorType">
<sequence>
<element ref="ds:KeyInfo"/>
...
```
if KeyDescriptor exists, then it must have a KeyInfo element.
The change is to delete[A] the `metadata` KeyDescriptor property if `decryptionPvk` is not supplied.
[A]: From oozcitak/xmlbuilder-js@9540ea487f954063df116c9a91f2914db31edcd6, null values will be preserved.
> skip KeyDescriptor if decryptionPvk is not provided

- lib/passport-saml/saml.js
- package.json
I did not write up a test case, but I did have to change this in my own implementation,
and it fixed the bug. If you'd like, I will attempt to write an actual test case.
This also more closely mimics the tests in xml-crypt, as [shown here](https://github.com/yaronn/xml-crypto/blob/master/test/saml-response-test.js#L8).
Not sure if anyone else has run into this issue, but I did in a separate project.
The issue is that when the signature node has been serialized to a String,
it loses the context of where it is in the XML tree. When deserialized, it
only knows about itself. Later in the code, in valdiateSignatureValue of xml-crypto,
this is called:
`var signedInfo = utils.findChilds(this.signatureNode, "SignedInfo")`
However, if the signature node has been serialized and deserialized, it …
> Fixed an obscure bug in which certificates may not be found.

- README.md
- lib/passport-saml/saml.js
- test/tests.js
This change mirrors `generateAuthorizeRequest`'s behavior of constructing `callbackUrl` from `protocol` and `path` if `callbackUrl` is not supplied.
I kept `req` independent from `generateServiceProviderMetaData` by adding a `host` option that defaults to `localhost`.
> generateServiceProviderMetadata: remove callbackUrl dependency

- lib/passport-saml/saml.js
- test/tests.js
Given the following SAML assertion
```xml
<saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Version="2.0" ID="_a293b185-490e-48ba-a30d-9ff96e9c5b2d" IssueInstant="2015-09-24T20:59:14Z">
<saml2:Issuer>http://stubidp.kentor.se/Metadata</saml2:Issuer>
<saml2:Subject>
<saml2:NameID>JohnDoe@example.com</saml2:NameID>
<saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"/>
</saml2:Subject>
<saml2:Conditions NotOnOrAfter="2015-09-24T21:01:14Z"/>
<saml2:AttributeStatement>
<saml2:Attribute Name="email">
<saml2:AttributeValue>JohnDoe@example.com</saml2:AttributeValue>
</saml2:Attribute>
</saml2:AttributeStatement>
<saml2:AttributeStatement>
<saml2:Attribute Name="uid">
<saml2:AttributeValue>12345</saml2:AttributeValue>
</saml2:Attribute> …
```
> Process all attribute statements instead of only first

- package.json
The comparison from [0.6.1 to 0.8](https://github.com/yaronn/xml-crypto/compare/f79385dc364135bd16ff44eb13db01e85bb40b76...93891c7173053f73b2739ac222600ee77fc90a41).
As far as I can tell, the only functional changes are:
* yaronn/xml-crypto@da0d09a8b028d5de90a39da8bca24530af399f12 (fixes yaronn/xml-crypto#70)
* yaronn/xml-crypto@d1ddec98eadd78b9f74a0c1aa91223117efe966e
* yaronn/xml-crypto@c6f7aaad7685502101e19f827fa5c001029b4519
> xml-crypto: update to 0.8

- lib/passport-saml/saml.js
- test/static/response-with-uncomplete-attribute.xml
- test/tests.js
A childless attribute (without attributeValue child node) like :
```
<AttributeStatement>
<Attribute Name="fubar.roles"/>
....
</AttributeStatement>
```
would cause a typeError in saml.js#L582. this fix would ignore such attribute
> Ignore attribute with no attributeValue child

- README.md
Some providers don't support SAML compression, or they don't support compressed SAML requests if the assertions is configured to be uncompressed.
So having the skipRequestCompression is nice, and highlighting it in documentation makes it easier for people configuring an SP app through trail and error (not all IDPs gives much in terms of error codes and error messages).
----
I ran into this issue when setting up and app to work with okta. Except for the SAML request compression issue this library works great (granted I had to contact okta support got even figure out that request compression was an issue, but that's their fault for not having error codes, system logs or debug information of any kind).
> Document the skipRequestCompression

- lib/passport-saml/saml.js
- test/tests.js
When using a custom query string parameter ADFS requires that only the SAMLRequest, RelayState, and SigAlg parameters be signed. Thus, this code was modified to not sign any custom query string parameters.
> Do not sign custom query string parameters

- lib/passport-saml/saml.js
- test/tests.js
The nameID element of the authn response can contain the NameQualifier and
SPNameQualifier attribute optionally. 
[pysaml2](https://github.com/rohe/pysaml2) however, which we use to implement our identity provider, depends on these attributes being present on the logout request. So can we please add this to the logout request?
> Add NameQualifier and SPNameQualifier to nameID

- lib/passport-saml/saml.js
- lib/passport-saml/strategy.js
- package.json
See also: [HTTP POST Binding in passport-saml #90](https://github.com/bergie/passport-saml/issues/90)
In some environments, the IdP requires HTTP-POST binding for all requests including the SAML  &lt;AuthnRequest&gt;.
In this scenario, the SP should send an HTML form back to the browser in the HTTP response. The HTML form contains a SAML &lt;AuthnRequest&gt; message encoded as the value of a hidden form control named SAMLRequest. For example:
```html
<html>
<body onload="document.forms[0].submit()">
<form method="post" action="https://idp.example.com/simplesaml/saml2/idp/SSOService.php">
<input type="hidden" name="SAMLRequest" value="request" />
<input type="hidden" name="RelayState" value="token" />
<input type="submit" value="Submit" />
</form> …
```
> Adds HTTP-POST binding support for the SAML <AuthnRequest>

- lib/passport-saml/saml.js
The `if (subject)` block is extended to cover all access to `subject`.
We ran into this bug in the code because our SAML provider didn't include Subject at the root of the Assertion -> line 614 throws a 'cannot access 0 of undefined' error.
> Fix Subject dereference bug

- package.json
There seems to be zero uses for ejs package, so this PR removes the unused devDependency from package.json.
Fixes #177 by kevinbror.
> Remove unused ejs package from devDeps

- lib/passport-saml/saml.js
- test/tests.js
trap exceptions thrown by signRequest which can occurr when an invalid
privateCert is passed to the saml object. Instead of throwing an
exception pass the error along via the supplied callback
added spec to check that the callback his hit with the error condtion when
calling requestToUrl on the saml object
Address issue: https://github.com/bergie/passport-saml/issues/230
> handle bad privateCert

- lib/passport-saml/saml.js
- test/tests.js
Math.random is not cryptographically secure, and IDs generated with it could potentially be predicted. Use crypto.randomBytes instead.
I kept the length of the generated ID the same, but it might also be worth increasing it if that's OK everywhere this function is used, as 20 hex chars is only an 80 bit ID, for which collisions could conceivably occur with a realistic number of stored IDs.
> Use crypto.randomBytes for ID generation

- README.md
- lib/passport-saml/saml.js
- test/tests.js
In our organisation we roll the signing certificate for our ADFS servers every year.  During the roll over period the server provides two certificates which may be valid, so when a SAML response is provided it is valid if it is signed with either of those signatures.
This change has two methods that can be used when `passport-saml` is used by a long running service that will persist over the certificate roll over period.  The first change is to allow the `cert` configuration key to be an array, this allows for the old and new certificates to be checked during the roll over period.  The second change is to allow the `cert` configuration key to be a function that returns the valid certificate or certificates, this allows the service to poll the ADFS server for what the valid certificates …
> Support multiple and dynamic signing certificates

- README.md
- lib/passport-saml/saml.js
- test/tests.js
This adds the optional check for SAML AudienceRestriction (see README).
- if `Audience` doesn't match the expected `options.audience` the SAML response is rejected
- if `options.audience` is specified, and SAML response doesn't have an `AudienceRestriction` it is rejected
> Audience validation

- README.md
- lib/passport-saml/strategy.js
Using this option, you can instantiate the strategy multiple times with
different configurations.
> New Feature: allow customizing the name of the strategy.

- README.md
- lib/passport-saml/saml.js
- test/tests.js
This addresses issue #181 and supersedes PR #183. Please see those other two entries for context.
> support multiple authnContext

- README.md
- lib/passport-saml/saml.js
- lib/passport-saml/strategy.js
- package.json
- test/samlTests.js
- test/tests.js
In order to include information specific to a request in the URL, for example, a query string parameter to pre-populate the username field on the IdP, the URL needs to be built with parameters available only when the `authenticate` method is called. Currently only parameters available at application start are available to be added as query string parameters when the URL is built.
> Include support for run-time params to be included in the generated URLs

- README.md
- lib/passport-saml/saml.js
- test/tests.js
This supersedes PR #269 and relates to issue #267. Please see those items for a discussion of this PR.
> entryPoint is compulsory for signed requests

- README.md
- lib/passport-saml/saml.js
This relates to the discussion in #278 .
> Extend and document the profile object

- README.md
- lib/passport-saml/saml.js
- lib/passport-saml/strategy.js
- test/static/expectedMetadataWithBothKeys.xml
- test/tests.js
Continue previous PR 275
https://github.com/bergie/passport-saml/pull/275
Made errors while rebasing the previous PR.
So I made another branch with only one commit issued from base master branch.
Hope everything is OK.
> Adds signing key in the metadata service provider generation.

- lib/passport-saml/saml.js
microsoft outlook returns
`nameQualifier`
`spNameQualifier`
as `null` instead of `undefined`
so this PR address this to handle both null and undefined
> feat(logout): handle null and undefined on nameQualifier

- README.md
- lib/passport-saml/saml.js
- test/tests.js
I've added documentation on `samlIssuer` and also made its validation optional (just as `InResponseTo`). This should actually be a part of https://github.com/bergie/passport-saml/pull/277
> Validate issuer on logout requests/responses if configured

- README.md
- lib/passport-saml/saml.js
This add the ability to extract the original SamlResponseXML as a method in the profile object.
Closes #328
> Add SamlResponseXML method to profile object

- README.md
- multiSamlStrategy.js
- test/multiSamlStrategy.js
Either use cache provided by user, or a default memory
cache to store InResponse parameters. This cache is not
yet partitioned per provider, which means a malicious
provider could do replay attacks by using anothers
unconsummed `InResponse` values
https://github.com/bergie/passport-saml/issues/334
> Support InResponseTo validations in MultiSaml

- package.json
This change incorporates a revert that fixes the problem discussed on 
yaronn/xml-crypto#167. It also drops xpath.js in favour of xpath, which
everybody else uses.
Fixes #324
> Upgrade xml-crypto to 1.1.2

- README.md
If the body parser is not used, the authentication callback will fail to find request.body, forcing it to redirect to IDP entry point. Which then POSTs to callback URL and hence the infinite redirect continues.
> Fix #128 documentation for body-parser dependancy

- README.md
- multiSamlStrategy.js
- test/multiSamlStrategy.js
This adds a function to pass in a request along with the other `generateServiceProviderMetadata` arguments to retrieve provider metadata when using the MultiSamlStrategy. If there is no request, we cannot call the `_getSamlOptions`-function to retrieve all the necessary options to call the `generateServiceProviderMetadata`-function with.
> Create a way to get provider metadata when using the MultiSamlStrategy

- .gitignore
- lib/passport-saml/saml.js
By setting explicitChars to true whenever xml2js is used and always use ._ to access values incosistent checks for [0] and [0]._ are eliminated.
Not broken test that were not broken from before.
Could have set .$ and ._ to .attrs and .chars or something instead but to fix the inconsistensies in the issues this was not necessary.
> Set explicitChar: true to make XML parsing consistent. Fixes issue #283 and #187

- lib/passport-saml/saml.js
- multiSamlStrategy.js
- test/multiSamlStrategy.js
- test/samlTests.js
- test/tests.js
There were two bugs in the code that were causing the tests to fail. Due to the way the tests were written tests failed as timeouts. I've also adjusted the tests so that when they fail they give useful information.
No functional changes were made to the test. The only changes were to correctly wrap async exception throwing blocks in a `try...catch` and then call `done()` properly so that `mocha` could properly report the error instead of having to wait 2 seconds for timeout and then reporting that instead of the actual error that occured.
> Fix broken tests

- lib/passport-saml/saml.js
- test/tests.js
InResponseTo value is used to verify that the response is for a valid request. If InResponseTo doesn't match a request the response is invalid. This is a cheap verification before more expensive cryptographical validation.
If cryptographical validation fails the response is most likely invalid and the corresponding InResponseTo value should be removed so no further calls can be made using it.
> Remove InResponseTo value if response validation fails

- lib/passport-saml/saml.js
https://github.com/bergie/passport-saml/issues/338
When identifierFormat: null the passport-saml generated metadata with a tag `<NameIDFormat/>` which causes an error in AD FS: `The value 'NameIDFormat' must be an absolute URI`.
Setting the identifierFormat: urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified allows importing the metadata file successfully.
> NameIDFormat fix

- .editorconfig
Using the same rules as nodejs.
> Add .editorconfig as suggested in #373

- .travis.yml
Support for Node 6 was dropped in dd1699ac04ec3968f8a6c763138e6503e160eec4
> Fix minimum version of Node.js in Travis

- package.json
This update will pick up the following changes:
yaronn/xml-crypto#171
yaronn/xml-crypto#179
yaronn/xml-crypto#183
> Bring-up xml-crypto to 1.4.0

- README.md
- lib/passport-saml/algorithms.js
- lib/passport-saml/saml-post-signing.js
- lib/passport-saml/saml.js
- test/saml-post-signing-tests.js
This commit adds support for signing AuthnRequests in the SAML HTTP-POST
binding. In the POST Binding the signature sits inside the SAML message
(as opposed to the Redirect binding, where the signture lives in the
URL's query string).
This will help suppport identity providers that require signed
AuthnRequests over the HTTP-POST binding.
Two new configuration options have been added:
* `digestAlgorithm`: allows you to specify the digest algorithm for the
signature.
* `xmlSignatureTransforms`: allows you to configure which XML transforms
to use.
> Issue #206: Support signing AuthnRequests using the HTTP-POST Binding

- README.md
- lib/passport-saml/saml.js
- test/static/logout_request_with_encrypted_name_id.xml
- test/tests.js
Add functionality to handle encrypted nameID on IdP-Initiated SLO. 
PR is literally updated version of stale #345 with added test. 
Test xml was generated with onelogin saml tools. 
All credits to @siren. 
Fixes #196
> add support for encrypted nameIDs in SLO request handling

- README.md
- lib/passport-saml/saml.js
- test/tests.js
allow `privateCert` to be passed in as base64 string without PEM formatting the same as `cert`.
> convert privateCert to PEM for signing

- lib/passport-saml/saml.js
The PR fixes a wrong check on attributeConsumingServiceIndex which can be zero.
> attributeConsumingServiceIndex can be zero

- test/tests.js
This just adds some tests to validate that we are not only requesting a logout correctly but we are responding correctly. This helps validate single-logout flows.
> Add tests to check for correct logout

- README.md
- multiSamlStrategy.js
- test/multiSamlStrategy.js
https://github.com/bergie/passport-saml/issues/425
> Fix multi saml strategy race conditions

- lib/passport-saml/saml.js
- test/tests.js
Closes: #245 
[saml-core-2.0-os](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) Section 2.7.3.1.1 says
```
The <AttributeValue> element supplies the value of a specified SAML attribute. It is of the
xs:anyType type, which allows any well-formed XML to appear as the content of the element.
```
This PR modifies the `attrValueMapper` function to return an object representing the parsed XML unless the attribute is a simple string, in which case the string is returned.
A test is included which also serves as an example of how this functionality can be used in the specific case of the deprecated [eduPersonTargetedID](https://wiki.refeds.org/display/STAN/eduPerson+2020-01#eduPerson2020-01-eduPersonTargetedID) attribute.
> Return object for XML-valued AttributeValues

- lib/passport-saml/saml.js
- test/tests.js
the callback invocation was being missed in case of errors during the NameID decryption
> fix: add catch block to NameID decryption

- .github/workflows/workflow.yml
- README.md
Travis CI had been removed when project was renamed to node-saml and thus tests are not run anymore to verify package state. This PR replaces Travis CI with GitHub Actions as it does the job and keeps everything in one place.
The CI task runs lint and tests on Node.js 10 and 12. Build Status is shown in a badge.
> Add GitHub Actions as Continuos Integration provider

- docs/adfs/retrieve_adfs_certificate.sh
Hi!
First of all, thanks for this come in hand script.
---------------
This fix try to use `curl` when `wget` is not installed.
the second `grep` is to solve this little problem.
> try to use curl when wget is not available

- package.json
Node 8 LTS has been EOL since 2019-12-31. Current LTS is Node >=10, see: https://github.com/nodejs/Release.
Also the library doesn't build on Node 8: "error chalk@4.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.10.0""
> Drop support for Node 8

- src/passport-saml/index.ts
- src/passport-saml/inmemory-cache-provider.ts
- src/passport-saml/strategy.ts
- src/passport-saml/types.ts
Before I did not include typings in package.json, but typescript still detects new definitions and turns off @types/passport-saml package
This PR adds compatibility with @types/passport-saml
- Issue Addressed: [#475]
- Tests included? [in #475]
> compatibility with @types/passport-saml, fixes #475

- package-lock.json
- package.json
- src/passport-saml/saml.ts
Q functions were replaced with corresponding native alternatives,
switching to async/await is not part of this PR
> outdated Q library was removed

- src/passport-saml/algorithms.ts
- src/passport-saml/index.ts
- src/passport-saml/multiSamlStrategy.ts
- src/passport-saml/saml.ts
- src/passport-saml/strategy.ts
- src/passport-saml/types.ts
- tsconfig.json
This patch disables the `esmoduleInterop` setting that causes type issues when the library is used by applications that do not transform their code in this way.
Note the workaround for the `strategy.ts` file (import = require()) is not ideal, but the export in that file is not a valid ES export, so using this TS workaround to get past it.
fixes: #482
> fix: disable esmoduleInterop setting

- README.md
- src/passport-saml/saml.ts
- src/passport-saml/types.ts
- test/tests.js
Hi everybody,
In my case, the configured IDP in passport-saml is a proxying IDP. This IDP manages the connection with several underlying IDP's. 
In some usecases, you want to target a specific IDP from within the application logic. This can be accomplished by targeting a IDP by IDPScoping. I added the option 'idpScopingProviderId' to the additonalSamlBehavior options that adds a node to the SAML AuthnRequest.
It would be very helpfull if this (relative small) feature could be merged in!
Greetings,
Rob
> feat(authorize-request): idp scoping provider

- src/passport-saml/saml.ts
- test/tests.js
While JS *technically* allows code to throw anything (including undefined/null/NaN), it's often considered bad practice. It's very annoying to handle/log errors from a library that sometimes throws strings and sometimes objects, and there's also no stack trace in string errors to help with debugging.
I realize this might be a controversial change, and it can break existing error handling code that assumes strings are thrown in some of the cases. But maybe it could be at least considered for 2.0?
More information:
https://eslint.org/docs/rules/no-throw-literal
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error
> Always throw error objects instead of strings

- tsconfig.json
Typescript source code is inlined inside source map
> inlineSources option for better source maps

- README.md
- src/passport-saml/saml-post-signing.ts
- src/passport-saml/saml.ts
- test/saml-post-signing-tests.js
- test/tests.js
An updated PR to address the conversation here: https://github.com/node-saml/passport-saml/pull/387
> Allow for use of privateKey instead of privateCert

- src/passport-saml/saml.ts
- test/test-signatures.js
Resolves https://github.com/node-saml/passport-saml/issues/431
- Issue Addressed: [X]
- Tests included? [X]
> normalize line endings before signature validation

- src/passport-saml/index.ts
A while ago I added PR #490 which was closed then because of the pending PR with a major Typescript refactor. After installing this refactor I still think the export of the MultiSamlStrategy class isn't complete. This PR adds the (in my opinion) missing export. Without this export, I have to import the MultiSamlStrategy from the deep located file 'passport-saml/lib/passport-saml/multiSamlStrategy' which causes the following TSLint error in my IDE: 
With the added export in this PR it is possible to do the import as following:
```javascript
import { MultiSamlStrategy } from 'passport-saml/lib/passport-saml';
```
> fix(typing): multi saml stratey export

- README.md
"confguration" --> "configuration"
> minor - fix typo in README

- package.json
- src/passport-saml/multiSamlStrategy.ts
1) Currently, we are forced to use ts-expect-error for multi-saml configuration because it extends the method in the base class with a completely different signature. But this ts-expect-error was not propagated to typescript definitions files. This PR makes things even worse - it uses undocumented feature of TS to propagate ts-expect-error in the definitions
2) to be able to use passport-saml from github I've changed tsc command from `prepublishonly` to `prepack` step. In this case tsc will run when package is installed directly from github
In v3 I suggest to change `generateServiceProviderMetadata` in multisaml strategy to `generateServiceProviderMetadataAsync` and add a stub with error message fro `generateServiceProviderMetadata`
- Issue Addressed: [ ]
- Tests …
> add ts-ignore to generated type definitions for multisaml strategy

- README.md
- src/passport-saml/types.ts
Fix in the README example of the scoping option which I previously added in a different PR.
> docs(scoping): fix for example

- src/passport-saml/multiSamlStrategy.ts
- src/passport-saml/types.ts
A MultiSamlConfig has a getSamlOptions member, but its type is not exported. Exporting these typings allows TypeScript projects to reference the original definition.
For example:
```
import { MultiSamlStrategy } from "passport-saml";
import type { MultiSamlConfig, SamlOptionsCallback } from "passport-saml/lib/passport-saml/types";
function getSamlOptions(req: express.Request, done: SamlOptionsCallback): void {
// Implementation
}
const config: MultiSamlConfig = { getSamlOptions };
const strategy: MultiSamlStrategy = new MultiSamlStrategy(config, verify);
```
- Issue Addressed: [ ]
> fix(typing): Export Multi SAML types

- src/passport-saml/saml-post-signing.ts
- src/passport-saml/saml.ts
- src/passport-saml/types.ts
Strategy and MultiSamlStrategy accept an "options" parameter with three fields which are used locally by the strategy, and remaining fields which are passed on to the SAML constructor.
There was an issue where certain fields (e.g. `privateKey`) could not be passed to the Strategy constructor but had to be passed on to the SAML constructor. This fixes that more thoroughly than #497, also fixing the type of `authnContext`, the limited string parameters, and adding `xmlSignatureTransforms`, `digestAlgorithm` and `disableRequestACSUrl`. 
> fix: derive SamlConfig from SAMLOptions

- src/passport-saml/saml.ts
- test/static/signatures/valid/response.root-signed.assertion-signed.xml
Resolves https://github.com/node-saml/passport-saml/issues/511
- Issue Addressed: [X]
- Tests included? [X]
> normalize signature line endings before loading signature block to xml-crypto

- package-lock.json
- package.json
- src/passport-saml/saml.ts
I noticed that you were ignoring errors from `xml-encryption` not having types. `xml-encryption` now has types, so those can be used instead.
> dev: add @types/xml-encryption

- .github/pull_request_template.md
- src/passport-saml/index.ts
Quite similar to #476 
Maintainers of the @types/passport-saml package exported the `SamlConfig` type: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-saml/index.d.ts#L39
Passport-SAML-Metadata (https://github.com/compwright/passport-saml-metadata) which depends on this package@latest and, more importantly, its types were referring to that interface.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-saml-metadata/src/metadata.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-saml-metadata/src/passport.d.ts
(Never mind my own code using this interface for convenience reasons as well.)
Re-Exporting the `SamlConfig` interface will resolve TypeScript compilation issues.
This …
> Reexport SamlConfig type to solve a regression in consumer packages

- src/passport-saml/saml.ts
To make saml.ts maintainable I've added async/await support for saml.ts
1. Old methods contain just `util.callbackify` function, which calls async `methodNameAsync` method
2. Old methods marked as deprecated (do we need to mark them this way?)
Pros:
* less useless code (no checks for errors, then, catch, helper functions to deal with promises and zlib.inflate). -95 lines if we don't count deprecated callback functions (-30 if we count them)
* the code left is written vertically, not diagonally
* better stack traces
Cons:
* too much changed for a single PR
> async/await for saml.ts

- README.md
- multiSamlStrategy.d.ts
- multiSamlStrategy.js
- test/multiSamlStrategy.js
passport-saml/multiSamlStrategy.js is something I'd like to remove:
1. it contains nothing, just import
2. it is outside of the source root and tsc/other tools don't include this file
3. old import depends on internal structure of the project
4. it uses module-level export
For now let's keep the file for compatibility, but let's update README so new people will not use the old way
> Update readme on using multiSamlStrategy

- src/passport-saml/inmemory-cache-provider.ts
- src/passport-saml/saml.ts
- test/tests.js
Currently, the cache interface is a very important part of this module because the default one is not usable in the production environment.
For compatibility reasons the interface was kept callback-based, despite the module itself uses async/await under the hood. For v3 I propose this breaking change to simplify our and users' code
> async / await in cache interface

- package-lock.json
- package.json
xmldom versions <= 0.4.0 have security issue. Update xmldom dependency to 0.5.x and bump package version. 
More information: https://github.com/xmldom/xmldom/security/advisories/GHSA-h6q6-9hqw-rwfv
After this fix as been merged, a new version of passport-saml should be released to npm.
> bump xmldom to 0.5.x since all lower versions have security issue

- package-lock.json
- package.json
This is a cherry-pick of the commit introduced by #551 on tag v2.0.5, so a v2.0.6 can be released with the security fix (while waiting for a 3.x release).
This targets new branch `2.x`. I can reopen a PR on `v2` if that's better after all (See https://github.com/node-saml/passport-saml/pull/552)
> bump xmldom to 0.5.x since all lower versions have security issue (#551)

- package-lock.json
- package.json
This time no `npm dedup` which seems to mess things up for some reasons.
> Update xml-encryption to v1.2.3 (branch 2.x)

- .gitignore
- package.json
The current lint rule misses most of the interesting lint errors (in src/) :)
> Fix lint npm script to match all files including in src/

- test/test-signatures.spec.ts
This caused the tests to fail when run with a recent version of mocha/ts-node
See also https://github.com/node-saml/passport-saml/pull/570
> Fix incorrect import of compiled files in tests

- README.md
- docs/adfs/README.md
- src/passport-saml/saml.ts
- src/passport-saml/types.ts
- test/tests.js
This simply renames option names and adds deprecation notices to help people prepare for 3.x
- disableRequestACSUrl -> disableRequestAcsUrl
- RACComparison -> racComparison
> Add deprecation notices for renamed variables

- CODE_OF_CONDUCT.md
This is the standard Code of Conduct that Github recommends and I endorse. It's based on this, which is in turn based on Mozilla policies.
https://www.contributor-covenant.org/version/2/0/code_of_conduct/
> Create of Code of Conduct

- src/passport-saml/saml.ts
- test/test-signatures.js
This is a 2.x backport of https://github.com/node-saml/passport-saml/pull/576.
Resolves https://github.com/node-saml/passport-saml/issues/575. See that issue for background.
This adds XML normalization to validateSignatureForCert before sending it to xml-crypto. It uses DOMParser for normalization tasks such as replacement of XML-encoded entities (&#13;) with their actual representations (carriage return).
- Issue Addressed: [X]
- Tests included? [X]
- Documentation updated? N/A
> Resolve XML-encoded carriage returns during signature validation (2.x)

- src/node-saml/saml.ts
- test/node-saml/test-signatures.spec.ts
See https://github.com/node-saml/passport-saml/issues/575 for background. This PR duplicates https://github.com/node-saml/passport-saml/pull/578 for `master`.
This adds XML normalization to `validateSignatureForCert` before sending it to `xml-crypto`. It uses `DOMParser` for normalization tasks such as replacement of XML-encoded entities (`&#13;`) with their actual representations (carriage return).
- Issue Addressed: [X]
- Tests included? [X]
- Documentation updated? N/A
> Resolve XML-encoded carriage returns during signature validation

- src/passport-saml/index.ts
- src/passport-saml/multiSamlStrategy.ts
- src/passport-saml/strategy.ts
- test/passport-saml/multiSamlStrategy.spec.ts
The goal of this PR is to improve the typing of the Strategy class hierarchy.
The current expected ts error causes problems with some earlier version of TS. 
```
[watch:ts] node_modules/passport-saml/lib/passport-saml/multiSamlStrategy.d.ts(10,5): error TS2416: Property 'generateServiceProviderMetadata' in type 'MultiSamlStrategy' is not assignable to the same property in base type 'Strategy'.
[watch:ts]   Type '(req: Request, decryptionCert: string, signingCert: string, callback: (err: Error, metadata?: string) => void) => void' is not assignable to type '(decryptionCert: string, signingCert?: string) => string'.
```
See https://github.com/node-saml/passport-saml/issues/540 which seems to be affected by this too.
Also, it does not make any sense to have a method override a method with a …
> Improve the typing of the Strategy class hierarchy.

- src/node-saml/saml-post-signing.ts
- src/node-saml/saml.ts
- src/node-saml/types.ts
- src/node-saml/utility.ts
- src/node-saml/xml.ts
- src/passport-saml/types.ts
- test/node-saml/saml-post-signing-tests.spec.ts
This PR moves most of the XML but non SAML logic to a dedicated file. It tries to improve some types when it's possible. 
The idea is:
1- to isolate dependencies, which I think is always a good idea. Especially when those dependencies are non in TS, this allows to group the "typing danger  zone"
2- shrink saml.ts by moving as much as possible non SAML related logic out.
This PR should not break anything and is done without updating any tests as a result.
Possible follow ups:
- Create a similar crypto-utils for everything crypto (PEM conversion, etc)
- See if xmlbuilder dependency could be dropped in favor of xml2js builder (which is built using xmlbuilder I think). This would avoid depending on 2 different version of xmlbuilder (v15 as a direct dep, v11 via xml2js)
This PR is best …
> Move XML functions to utility module

- src/node-saml/saml.ts
When validateInResponseTo isn't set to `true`, we end up setting it to `false` here: https://github.com/node-saml/passport-saml/blob/13c7216644ba055217fc97b41df63301be982137/src/node-saml/saml.ts#L155
This value was then checked if it's not `null` here, which is always true. The intention was likely to have this check check if the value was true, like everywhere else this value is used. This changes the gate to just check if the value is true.
This is a small enough change so I won't default to writing a test for this edge behavior - an extra delete call to the cache provider isn't a big deal, but I found this when debugging our custom cache provider.
> Fix validateInResponseTo null check

- README.md
Cache Provider interface has changed in #532 . This updates the readme to use the new interface.
> Update README with new Cache Provider interface

- README.md
Just fixing a small typo in the docs.
> Fix typo OnBefore -> NotBefore

- CHANGELOG.md
This is a rebuilt changelog for 3.0.0. This was built using a bunch of bug fixes in a private branch of `github-release-notes`. These fixes have been requested in a set of chained PRs started with [this](https://github.com/github-tools/github-release-notes/pull/301) one.
> Rebuild changelog for 3.0.0

- .gitignore
- src/node-saml/saml.ts
- test/node-saml/tests.spec.ts
https://github.com/node-saml/passport-saml/blob/f1a436fa243080f8cfcf06fd0f40ce3af396c8b6/src/passport-saml/saml.ts#L1319
It is currently possible to override some default properties of the `profile` object in `processValidlySignedAssertionAsync` method.
This can be done if any property like `Issuer` is also present in the attribute mapping. The expected behavior here should be that the properties (`Issuer`, `inResponseTo`, `sessionIndex`, `nameID`, `nameIDFormat`, `nameQualifier`, `spNameQualifier`) will probably already be present in the profile, and in that case they shouldn't be overridden by the same named attribute in attribute mapping.
This issue can be handled gracefully by simply skipping the value from attribute mapping or an error can be thrown. This PR handles the issue …
> Fix: Conflicting profile properties between profile and attributes

- src/node-saml/saml.ts
- test/node-saml/test-signatures.spec.ts
- test/static/signatures/invalid/response.root-signed-transforms.assertion-unsigned.xml
- test/static/signatures/invalid/response.root-unsigned.assertion-signed-transforms.xml
As far as I know a WebSSO profile shouldn't have more than 2 Transform, at most an "enveloped-signature" and an exclusive canonicalization transform. A SAMLResponse can force xml-crypto to needlessly spend time, bound only by POST size constraints.
All tests pass.
> Limit transforms for signed nodes

- package.json
The main path in package.json needs to be updated for the recent changes to package structure. (`./lib/passport-saml` no longer exists, now the root is in `./lib`)
> Fix main path in package.json

- src/node-saml/saml.ts
- test/static/expected metadata.xml
- test/static/expectedMetadataWithBothKeys.xml
This PR patches in 3.x [the bug raised](https://github.com/node-saml/node-saml/issues/13) (and fixed) in `node-saml`. It updates the algorithm references to the correct paths, and updates relevant tests:
http://www.w3.org/2001/04/xmlenc#aes256-gcm > http://www.w3.org/2009/xmlenc11#aes256-gcm
http://www.w3.org/2001/04/xmlenc#aes128-gcm > http://www.w3.org/2009/xmlenc11#aes128-gcm
Issue Addressed: [X]
Link to SAML spec: [X] ([XML Encryption Syntax and Processing Version 1.1](https://www.w3.org/TR/xmlenc-core1/#sec-AES-GCM))
Tests included? [X]
Documentation updated? [X] (No changes found)
> Patch algorithm definitions

- README.md
- package-lock.json
- package.json
- src/multiSamlStrategy.ts
- src/strategy.ts
- src/types.ts
This is some code clean-up to prepare for a follow-on PR to enable logout validation. This cleans up the README, adds some more types, and removes some linter warnings.
> Code cleanup in preparation for logout validation

- README.md
- src/multiSamlStrategy.ts
- src/strategy.ts
This PR adds the ability to pass an array of signing certs when generating SAML metadata.  This makes it possible to do signing certificate rotation with IdPs that poll for metadata updates.
See the PR in [node-saml](https://github.com/node-saml/node-saml/pull/23 ) for more details.
- Link to SAML spec: [n/a]
- Tests included? [n/a]
- Documentation updated? [x]
> Add support for multiple signing certs in metadata

- README.md
Document support for passive option in `node-saml`
Re: https://github.com/node-saml/node-saml/blob/master/src/saml.ts#L135
- Issue Addressed: []
- Link to SAML spec: []
- Tests included? []
- Documentation updated? [x]
> Document passive option

- package-lock.json
- package.json
This update actually /remove/ node forge to use native nodejs crypto instead. This is nice as node-forge is a fairly large module.
The major version bump in xml-encryption is because this update remove support for node < 12 (which are already not supported by passport-saml)
This PR is on the 3.x branch.
> Update xml-encryption to get rid of vulnerable node-forge

- src/index.ts
Exporting `MultiStrategyConfig` type from src index so the type is available and can be imported for segregating the code and be used like below
```
import { MultiSamlStrategy, VerifyWithRequest, MultiSamlConfig } from 'passport-saml';
const multiSamlOptions: MultiSamlConfig = {
passReqToCallback: true, // makes req available in callback
getSamlOptions: async (request, done) => {
const configuration = await findProvider(request);
return done(null, configuration);
},
};
export const multiSamlStrategy = new MultiSamlStrategy(multiSamlOptions, login);
```
- Issue Addressed: [ ]
> 🎨  add MultiStrategyConfig type export

- package-lock.json
- package.json
Update use of types to match the recommendations of TypeScript.
- Issue Addressed: [  #606 ]
- Link to spec: [ https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies ]
- Tests included? [ n/a ]
- Documentation updated? [ n/a ]
> Move TypeScript-required types to dependencies from devDependencies

- package-lock.json
- package.json
- test/capturedSamlRequests.spec.ts
- test/capturedSamlResponses.spec.ts
- test/multiSamlStrategy.spec.ts
Fixed https://github.com/node-saml/passport-saml/issues/653
I fixed it the same way as node-saml Issue. (https://github.com/node-saml/node-saml/pull/41)
There are some points that have been specially dealt with.
(1) In the following code, "match" was not used. The reason we did not use "match" in the following code is because, as shown in [this Issue](https://github.com/jmendiara/karma-jquery-chai/issues/3), if the comparison target is a string, an error like "TypeError: re.exec is not a function" will occur.
https://github.com/node-saml/passport-saml/pull/687/files#diff-855cb92ef30e211592bac8169dcf23d250f18e57f7f662bab42f31136b3794eeR234
(2) The following code does not use "startWith".The reason for this is that the same does not exist in chai as described in [this …
> Migrate from "should" to "chai"

- .mocharc.json
The `.mocharc.json` files uses an older spec. Update to use the newer specification.
See https://stackoverflow.com/a/71719457/271351
> Adjust .mochars.json

- docs/adfs/README.md
Update README to remove an insecure suggestion.
> Update README to remove an insecure suggestion

- README.md
Before, one of the first sentences in the documentation was a history note about a fork that was made 10 years ago. That's not one of the first things people need to know about the project.
Now, a note on the history of the project has been moved to the bottom and expanded to credit the primary maintainers throughout the last decade.
During this commit, the project is about to turn 10 years old in 2 days! 
The project was born on June 28th, 2012 with a commit by @bergie.
> docs: move history note to the bottom and expand it.

- README.md
Update badges to correspond to the new NPM package location.
> Update badges for scoped package

- .github/dependabot.yml
Have dependabot update the `package.json` file along with the `package-lock.json` file.
> Have dependabot update package.json too

- package.json
Add a prerelease script to build and test the code before releasing to make sure that everything is still good to go.
> Add prerelease script

- README.md
The README is a little unclear about how the sample code is supposed to work and it has some formatting issues. This correct both of those problems.
It still remains to remove all the information in this README that is also in the `node-saml` README. We should be referring people to that README instead of duplicating that here.
> Update README formatting and to provide clearer explanation of examples

- package-lock.json
- package.json
node-saml has been updated with a patch release to address a security concern. Set the minimum allowed version of node-saml to make sure we get that security patch.
> Use secure version of node-saml

- src/multiSamlStrategy.ts
- src/strategy.ts
Revised AbstractStrategy for authenticate method to match PassportStrategy expectation
The previous implementation was using the RequestWithUser internal type that contradict the base PassportStrategy authenticate given that user property SHOULD NOT be required for this process.
This causes a typings issue with the base passport which overrides the express Request interface to have a user property that is of type User | undefined;
- Issue Addressed: N/A
- Link to SAML spec: N/A
- Tests included? No, fixing a typings issue with core base package
- Documentation updated? Not needed, seamless change
> Revised AbstractStrategy for authenticate method to match PassportStrategy expectation

- .grenrc.js
- CHANGELOG.md
- package-lock.json
- package.json
@markstos , this is a PR that addresses your concerns mentioned in https://github.com/node-saml/passport-saml/issues/839#issuecomment-1582933682. If we want any of the lines in this changelog altered, we just have to change the name of the PR and regenerate the changelog.
I can do this same thing with `node-saml` if we like it.
> Roll-up changelog entries for beta releases

- src/types.ts
There was an unused type called `AuthorizeOptions`. Not only was it unused, but it also was redundant, adding no new typing information.
> Remove unused `AuthorizeOptions` type

- .prettierrc.json
- README.md
Update the README to point to `node-saml` documentation for configuration options that are passed through to `node-saml`.
> Update README to point to `node-saml` documentation

- README.md
Just a readme update to reflect the existing code. 
https://github.com/node-saml/node-saml/blob/master/CHANGELOG.md the changelog suggests path and cert have been replaced with callbackURL and idpCert.
> Update README.md to reflect updated node-saml
